{% set name = "pyasn1" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyasn1-{{ version }}.tar.gz
  sha256: 6f580d2bdd84365380830acf45550f2511469f673cb4a5ae3857a3170128b034

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyasn1
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyasn1/pyasn1
  summary: Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)
  dev_url: https://github.com/pyasn1/pyasn1
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - xhochy
