{% set name = "pyasn1" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyasn1-{{ version }}.tar.gz
  sha256: 3a35ab2c4b5ef98e17dfdec8ab074046fbda76e281c5a706ccd82328cfc8f64c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4,!=3.5
    - setuptools
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4,!=3.5

test:
  imports:
    - pyasn1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyasn1/pyasn1
  summary: Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)
  dev_url: https://github.com/pyasn1/pyasn1
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - xhochy
